try with bash only

diff --git a/.github/workflows/pythonapp.yml b/.github/workflows/pythonapp.yml
--- a/.github/workflows/pythonapp.yml
+++ b/.github/workflows/pythonapp.yml
@@ -28,20 +28,20 @@ jobs:
         pip install -r requirements.txt
         pip install pylint autopep8 mypy
 
+    # - name: PyLint
+    #   if: runner.os == 'Windows'
+    #   run: |
+    #     Get-ChildItem "blokus/**/*.py" -Recurse | ForEach-Object { Write-Host $_; pylint -s n $_; if (!$?) { $failed=$true }}; if ($failed) { exit 1 }
     - name: PyLint
-      if: runner.os == 'Windows'
-      run: |
-        Get-ChildItem "blokus/**/*.py" -Recurse | ForEach-Object { Write-Host $_; pylint -s n $_; if (!$?) { $failed=$true }}; if ($failed) { exit 1 }
-    - name: PyLint with pylint on ${{ matrix.runs-on }}
-      if: runner.os == 'Linux'
+      shell: bash
       run: |
         cd blokus && find . -type f -name "*.py" | xargs python3 -m pylint -s n
 
-    # - name: AutoPep8
+    # - name: AutoPep8 on ${{ matrix.runs-on }}
     #   if: runner.os == 'Windows'
     #   run: |
     #     $changes=(autopep8 --recursive --diff --aggressive blokus); if($changes -ne $null) { Write-Host $changes; exit 1 }
-    # - name: AutoPep8
+    # - name: AutoPep8 on ${{ matrix.runs-on }}
     #   if: runner.os == 'Linux'
     #   run: |
     #     changes=$(python3 -m autopep8 --recursive --diff --aggressive blokus); if [[ $changes ]]; then echo "$changes" && exit 1; fi
